with source_rows as (
    select
        raw_data,
        filename,
        loaded_at,
        try_to_timestamp_tz(raw_data:as_of::string) as tick_ts,
        raw_data:product_id::string as product_id,
        raw_data:feed_status::string as feed_status,
        raw_data:reason::string as feed_reason,
        try_to_number(raw_data:data_age_ms::string) as data_age_ms,
        try_to_decimal(raw_data:highest_bid:price::string, 38, 12) as bid_price,
        try_to_decimal(raw_data:highest_bid:quantity::string, 38, 12) as bid_qty,
        try_to_decimal(raw_data:lowest_ask:price::string, 38, 12) as ask_price,
        try_to_decimal(raw_data:lowest_ask:quantity::string, 38, 12) as ask_qty,
        try_to_decimal(raw_data:current_spread::string, 38, 12) as spread,
        try_to_decimal(raw_data:max_spread_since_start::string, 38, 12) as max_spread_since_start,
        try_to_decimal(raw_data:average_mid_price:"1m":value::string, 38, 12) as avg_mid_price_1m,
        try_to_decimal(raw_data:average_mid_price:"5m":value::string, 38, 12) as avg_mid_price_5m,
        try_to_decimal(raw_data:average_mid_price:"15m":value::string, 38, 12) as avg_mid_price_15m,
        try_to_decimal(raw_data:forecast_60s:value::string, 38, 12) as forecast_value,
        try_to_decimal(raw_data:forecast_60s:naive_value::string, 38, 12) as forecast_naive_value,
        raw_data:forecast_60s:model::string as forecast_model,
        raw_data:forecast_60s:status::string as forecast_status,
        try_to_timestamp_tz(raw_data:forecast_60s:target_at::string) as forecast_target_ts,
        try_to_decimal(raw_data:average_absolute_error:primary_1m:value::string, 38, 12) as primary_aae_1m,
        try_to_decimal(raw_data:average_absolute_error:primary_5m:value::string, 38, 12) as primary_aae_5m,
        try_to_decimal(raw_data:average_absolute_error:primary_15m:value::string, 38, 12) as primary_aae_15m,
        try_to_decimal(raw_data:average_absolute_error:naive_1m:value::string, 38, 12) as naive_aae_1m,
        try_to_decimal(raw_data:average_absolute_error:naive_5m:value::string, 38, 12) as naive_aae_5m,
        try_to_decimal(raw_data:average_absolute_error:naive_15m:value::string, 38, 12) as naive_aae_15m
    from {{ source('coinbase_raw', 'raw_stream') }}
)
select
    sha2(concat_ws('|', coalesce(filename, ''), coalesce(tick_ts::string, ''), coalesce(product_id, '')), 256) as snapshot_id,
    tick_ts,
    product_id,
    bid_price,
    bid_qty,
    ask_price,
    ask_qty,
    (bid_price + ask_price) / 2 as mid_price,
    spread,
    max_spread_since_start,
    avg_mid_price_1m,
    avg_mid_price_5m,
    avg_mid_price_15m,
    forecast_value,
    forecast_naive_value,
    forecast_model,
    forecast_status,
    forecast_target_ts,
    primary_aae_1m,
    primary_aae_5m,
    primary_aae_15m,
    naive_aae_1m,
    naive_aae_5m,
    naive_aae_15m,
    feed_status,
    feed_reason,
    data_age_ms,
    filename as source_filename,
    loaded_at
from source_rows
